"""Save bidder pubkey.

Revision ID: 0387087d8cfb
Revises: e3e271835296
Create Date: 2023-06-16 11:45:35.908510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0387087d8cfb'
down_revision = 'e3e271835296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buyer_nostr_public_key', sa.String(length=64), nullable=True))
        batch_op.alter_column('buyer_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.alter_column('buyer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('buyer_nostr_public_key')

    # ### end Alembic commands ###
