"""Add extra checks for verification phrase.

Revision ID: 03d388ba77ea
Revises: 1a2cb89c865c
Create Date: 2023-02-23 12:39:29.609692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03d388ba77ea'
down_revision = '1a2cb89c865c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nostr_auth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_phrase_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('verification_phrase_check_counter', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nostr_auth', schema=None) as batch_op:
        batch_op.drop_column('verification_phrase_check_counter')
        batch_op.drop_column('verification_phrase_sent_at')

    # ### end Alembic commands ###
