"""Add is_featured to auction.

Revision ID: 0b933fdb55c0
Revises: 9055e2033d85
Create Date: 2022-06-24 12:41:15.785471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b933fdb55c0'
down_revision = '9055e2033d85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auctions', sa.Column('is_featured', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auctions', 'is_featured')
    # ### end Alembic commands ###
