"""Deal with duplicate keys.

Revision ID: 0d4d373978f2
Revises: 53cbfe6a65f6
Create Date: 2023-04-10 19:44:29.716400

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0d4d373978f2'
down_revision = '53cbfe6a65f6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_new_lnauth_key')
        batch_op.create_index(batch_op.f('ix_users_new_lnauth_key'), ['new_lnauth_key'], unique=False)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_new_lnauth_key'))
        batch_op.create_index('ix_users_new_lnauth_key', ['new_lnauth_key'], unique=True)

    # ### end Alembic commands ###
