"""Nostr badges.

Revision ID: 0f52341f4fa1
Revises: f1b707c6dbe1
Create Date: 2023-08-29 13:11:43.074296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0f52341f4fa1'
down_revision = 'f1b707c6dbe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('badge_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=64), nullable=False),
    sa.Column('image_hash', sa.String(length=64), nullable=False),
    sa.Column('nostr_event_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('badge_id')
    )
    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_badges_nostr_event_id'), ['nostr_event_id'], unique=True)

    op.drop_table('user_badges')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_badges',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('badge', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('icon', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('awarded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_badges_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_badges_pkey')
    )
    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_badges_nostr_event_id'))

    op.drop_table('badges')
    # ### end Alembic commands ###
