"""Add campaign banner.

Revision ID: 17cfd040c3ea
Revises: 00b5877a8e77
Create Date: 2022-10-21 13:54:56.809544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17cfd040c3ea'
down_revision = '00b5877a8e77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('banner_url', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'banner_url')
    # ### end Alembic commands ###
