"""Add USD price to sales.

Revision ID: 1ce2e632ba08
Revises: c6d089d54e86
Create Date: 2022-09-19 09:30:18.098540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ce2e632ba08'
down_revision = 'c6d089d54e86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('price_usd', sa.Float(), server_default="0", nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'price_usd')
    # ### end Alembic commands ###
