"""Add xpub index.

Revision ID: 202641046e4c
Revises: c6d089d54e86
Create Date: 2022-08-25 12:52:03.415374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202641046e4c'
down_revision = 'c6d089d54e86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('xpub_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'xpub_index')
    # ### end Alembic commands ###
