"""Add instant_buy_price column to auction model.

Revision ID: 325df3b37192
Revises: 7b9b9d83c135
Create Date: 2022-07-04 13:23:32.575727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '325df3b37192'
down_revision = '7b9b9d83c135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auctions', sa.Column('instant_buy_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auctions', 'instant_buy_price')
    # ### end Alembic commands ###
