"""Add Order.paid_at.

Revision ID: 3bbdeac35736
Revises: dc75ae2f8b83
Create Date: 2023-05-23 12:17:38.892959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bbdeac35736'
down_revision = 'dc75ae2f8b83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('paid_at')

    # ### end Alembic commands ###
