"""Add user badges and rewards.

Revision ID: 3c9546a68f19
Revises: d2ef47758641
Create Date: 2022-11-17 12:25:49.328239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c9546a68f19'
down_revision = 'd2ef47758641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_badges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=32), nullable=False),
    sa.Column('awarded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sales', sa.Column('campaign_id', sa.Integer(), nullable=True))
    op.add_column('sales', sa.Column('desired_badge', sa.Integer(), nullable=True))
    op.alter_column('sales', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key('fk_sales_campaign_id', 'sales', 'campaigns', ['campaign_id'], ['id'])
    op.alter_column('bids', 'payment_request',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bids', 'payment_request',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.drop_constraint('fk_sales_campaign_id', 'sales', type_='foreignkey')
    op.alter_column('sales', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('sales', 'desired_badge')
    op.drop_column('sales', 'campaign_id')
    op.drop_table('user_badges')
    # ### end Alembic commands ###
