"""Add index.

Revision ID: 3e2210c258eb
Revises: 8662155d4e64
Create Date: 2023-07-29 14:35:48.711384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e2210c258eb'
down_revision = '8662155d4e64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bids_buyer_nostr_public_key'), ['buyer_nostr_public_key'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bids_buyer_nostr_public_key'))

    # ### end Alembic commands ###
