"""double auction description size

Revision ID: 3fe9c7f1c595
Revises: fc10599148c8
Create Date: 2022-08-11 21:20:05.169264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fe9c7f1c595'
down_revision = 'fc10599148c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auctions', 'description',
               existing_type=sa.VARCHAR(length=2100),
               type_=sa.String(length=4200),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auctions', 'description',
               existing_type=sa.String(length=4200),
               type_=sa.VARCHAR(length=2100),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###
