"""Make media editable.

Revision ID: 4586f6282d0b
Revises: d940f3567a1c
Create Date: 2022-10-03 12:47:23.581536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4586f6282d0b'
down_revision = 'd940f3567a1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('index', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('media', sa.Column('content_hash', sa.String(length=256), nullable=True))
    op.alter_column('media', 'twitter_media_key',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media', 'twitter_media_key',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('media', 'content_hash')
    op.drop_column('media', 'index')
    # ### end Alembic commands ###
