"""Add auctions to Order.

Revision ID: 4a22bfdccc90
Revises: 0387087d8cfb
Create Date: 2023-06-20 13:53:37.651003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a22bfdccc90'
down_revision = '0387087d8cfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auction_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'auctions', ['auction_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('auction_id')

    # ### end Alembic commands ###
