"""Store stall nostr event ID.

Revision ID: 4ba6c5d104b3
Revises: 3e2210c258eb
Create Date: 2023-08-15 14:36:10.113932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ba6c5d104b3'
down_revision = '3e2210c258eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stall_nostr_event_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_stall_nostr_event_id'), ['stall_nostr_event_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_stall_nostr_event_id'))
        batch_op.drop_column('stall_nostr_event_id')

    # ### end Alembic commands ###
