"""Nostr stalls.

Revision ID: 4c6c784e30e1
Revises: f0ccfd30d79e
Create Date: 2023-04-20 15:21:35.704877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c6c784e30e1'
down_revision = 'f0ccfd30d79e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stall_private_key', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_stall_private_key'), ['stall_private_key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_stall_private_key'))
        batch_op.drop_column('stall_private_key')

    # ### end Alembic commands ###
