"""Store badge purchase info.

Revision ID: 4ff050ac2527
Revises: 7bfdc024cc59
Create Date: 2024-01-23 08:19:43.372755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ff050ac2527'
down_revision = '7bfdc024cc59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stall_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('listing_uuid', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.drop_column('listing_uuid')
        batch_op.drop_column('stall_id')

    # ### end Alembic commands ###
