"""Ensure items on Auction and Media and drop hacks.

Revision ID: 526dd4c581ca
Revises: 842599b62770
Create Date: 2022-10-27 13:53:32.212894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526dd4c581ca'
down_revision = '842599b62770'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auctions', 'seller_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('auctions', 'title',
               existing_type=sa.VARCHAR(length=210),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('auctions', 'description',
               existing_type=sa.VARCHAR(length=21000),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('auctions', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('media', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('auctions', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('auctions', 'description',
               existing_type=sa.VARCHAR(length=21000),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('auctions', 'title',
               existing_type=sa.VARCHAR(length=210),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('auctions', 'seller_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
