"""Remove resume.

Revision ID: 53cbfe6a65f6
Revises: f95a9a40c00d
Create Date: 2023-04-07 09:49:49.880742

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '53cbfe6a65f6'
down_revision = 'f95a9a40c00d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_resume_portfolio')
    op.drop_table('user_resume_achievements')
    op.drop_table('user_resume_experience')
    op.drop_table('user_resume_skills')
    op.drop_table('user_resume_education')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('resume_desired_salary_usd')
        batch_op.drop_column('resume_bitcoiner_question')
        batch_op.drop_column('resume_bio')
        batch_op.drop_column('resume_job_title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_job_title', sa.VARCHAR(length=210), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('resume_bio', sa.VARCHAR(length=21000), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('resume_bitcoiner_question', sa.VARCHAR(length=2100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('resume_desired_salary_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    op.create_table('user_resume_education',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('education', sa.VARCHAR(length=210), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_resume_education_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_resume_education_pkey')
    )
    op.create_table('user_resume_skills',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skill', sa.VARCHAR(length=21), autoincrement=False, nullable=True),
    sa.Column('added_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_resume_skills_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_resume_skills_pkey')
    )
    op.create_table('user_resume_experience',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('from_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('from_month', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('to_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('to_month', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('job_title', sa.VARCHAR(length=210), autoincrement=False, nullable=False),
    sa.Column('organization', sa.VARCHAR(length=210), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=2100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_resume_experience_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_resume_experience_pkey')
    )
    op.create_table('user_resume_achievements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('achievement', sa.VARCHAR(length=210), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_resume_achievements_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_resume_achievements_pkey')
    )
    op.create_table('user_resume_portfolio',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=210), autoincrement=False, nullable=True),
    sa.Column('added_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_resume_portfolio_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_resume_portfolio_pkey')
    )
    # ### end Alembic commands ###
