"""User migration.

Revision ID: 5b918d4f5903
Revises: e90cd0b46e69
Create Date: 2023-10-03 10:50:56.342560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b918d4f5903'
down_revision = 'e90cd0b46e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('migrated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('migrated_to_user_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('migrated_to_user_id')
        batch_op.drop_column('migrated_at')

    # ### end Alembic commands ###
