"""Add wallet name.

Revision ID: 673138f33cbb
Revises: d9a75b8555ed
Create Date: 2023-08-17 14:01:44.314479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '673138f33cbb'
down_revision = 'd9a75b8555ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_name', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('wallet_name')

    # ### end Alembic commands ###
