"""Add contribution details on Auction.

Revision ID: 702d020df9ed
Revises: 81fd68652e8b
Create Date: 2022-05-19 08:54:48.258403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '702d020df9ed'
down_revision = '81fd68652e8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auctions', sa.Column('contribution_payment_request', sa.String(length=512), nullable=True))
    op.add_column('auctions', sa.Column('contribution_requested_at', sa.DateTime(), nullable=True))
    op.add_column('auctions', sa.Column('contribution_settled_at', sa.DateTime(), nullable=True))
    op.add_column('auctions', sa.Column('contribution_amount', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_auctions_contribution_payment_request'), 'auctions', ['contribution_payment_request'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auctions_contribution_payment_request'), table_name='auctions')
    op.drop_column('auctions', 'contribution_amount')
    op.drop_column('auctions', 'contribution_settled_at')
    op.drop_column('auctions', 'contribution_requested_at')
    op.drop_column('auctions', 'contribution_payment_request')
    # ### end Alembic commands ###
