"""Support digital items.

Revision ID: 7218961e6757
Revises: 5883dd3619bf
Create Date: 2023-11-29 11:50:18.521217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7218961e6757'
down_revision = '5883dd3619bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('digital_item_message', sa.String(length=2100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('digital_item_message')

    # ### end Alembic commands ###
