"""Add Twitter profile picture.

Revision ID: 788294334544
Revises: 3ab9cd7f2087
Create Date: 2022-05-10 10:12:02.900771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '788294334544'
down_revision = '3ab9cd7f2087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('twitter_profile_image_url', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'twitter_profile_image_url')
    # ### end Alembic commands ###
