"""add_created_at_to_invoices

Revision ID: 7cf1dc63f627
Revises: d5e446bf8a1b
Create Date: 2023-09-21 16:51:45.256047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cf1dc63f627'
down_revision = 'd5e446bf8a1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lightning_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lightning_invoices', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
