"""Add Auction.created_at.

Revision ID: 81fd68652e8b
Revises: 11234423a696
Create Date: 2022-05-11 08:34:54.371502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81fd68652e8b'
down_revision = '11234423a696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auctions', sa.Column('created_at', sa.DateTime(), nullable=False, server_default="now()"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auctions', 'created_at')
    # ### end Alembic commands ###
