"""Add item category.

Revision ID: 842599b62770
Revises: 17cfd040c3ea
Create Date: 2022-10-25 14:45:38.246788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '842599b62770'
down_revision = '17cfd040c3ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('category', sa.String(length=21), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'category')
    # ### end Alembic commands ###
