"""Add shipping location.

Revision ID: 9055e2033d85
Revises: 7cef5f311cbb
Create Date: 2022-06-08 07:28:16.731518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9055e2033d85'
down_revision = '7cef5f311cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auctions', sa.Column('shipping_from', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auctions', 'shipping_from')
    # ### end Alembic commands ###
