"""Differentiate cancellation from expiration.

Revision ID: a0a088a1ee6c
Revises: f4c195bdf6c4
Create Date: 2023-06-06 11:03:36.551824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0a088a1ee6c'
down_revision = 'f4c195bdf6c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canceled_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('canceled_at')

    # ### end Alembic commands ###
