"""Remove auction following.

Revision ID: a41ce996abe0
Revises: 27ee7cccbc44
Create Date: 2023-11-29 10:28:17.549641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a41ce996abe0'
down_revision = '27ee7cccbc44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_auctions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_auctions',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auction_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('following', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], name='user_auctions_auction_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_auctions_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'auction_id', name='user_auctions_pkey')
    )
    # ### end Alembic commands ###
