"""Add lock_expiry column and is_locked property to auction model.

Revision ID: a5db732683bd
Revises: 325df3b37192
Create Date: 2022-07-09 19:37:40.470509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5db732683bd'
down_revision = '325df3b37192'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auctions', sa.Column('lock_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auctions', 'lock_expiry')
    # ### end Alembic commands ###
