"""Add lightning address.

Revision ID: b06199cd8026
Revises: 3bbdeac35736
Create Date: 2023-05-31 10:10:42.840498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b06199cd8026'
down_revision = '3bbdeac35736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lightning_address', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('lightning_address')

    # ### end Alembic commands ###
