"""add store info to user

Revision ID: b1ad2f1195f5
Revises: 7fddb56a6944
Create Date: 2022-07-29 01:43:41.493864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1ad2f1195f5'
down_revision = '7fddb56a6944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('store_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('store_description', sa.String(length=240), nullable=True))
    op.create_index(op.f('ix_users_store_name'), 'users', ['store_name'], unique=True)
    op.create_unique_constraint(None, 'users', ['store_description'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_store_name'), table_name='users')
    op.drop_column('users', 'store_description')
    op.drop_column('users', 'store_name')
    # ### end Alembic commands ###
