"""Add stall settings.

Revision ID: b1b8a655e102
Revises: 1ce2e632ba08
Create Date: 2022-09-22 10:33:47.677597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1b8a655e102'
down_revision = '1ce2e632ba08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stall_banner_url', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stall_banner_url')
    # ### end Alembic commands ###
