"""Increase title and description length.

Revision ID: ba6b5760534a
Revises: 788294334544
Create Date: 2022-05-11 07:13:44.471568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba6b5760534a'
down_revision = '788294334544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auctions', 'title',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=210),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('auctions', 'description',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=2100),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auctions', 'description',
               existing_type=sa.String(length=2100),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('auctions', 'title',
               existing_type=sa.String(length=210),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###
