"""Increase description length.

Revision ID: c4493279d631
Revises: fc10599148c8
Create Date: 2022-08-16 06:39:15.095962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4493279d631'
down_revision = 'fc10599148c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auctions', 'description',
               existing_type=sa.VARCHAR(length=2100),
               type_=sa.String(length=21000),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('campaigns', 'description',
               existing_type=sa.VARCHAR(length=2100),
               type_=sa.String(length=21000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaigns', 'description',
               existing_type=sa.String(length=21000),
               type_=sa.VARCHAR(length=2100),
               existing_nullable=False)
    op.alter_column('auctions', 'description',
               existing_type=sa.String(length=21000),
               type_=sa.VARCHAR(length=2100),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###
