"""Add user skills and achievements.

Revision ID: c757a5632f69
Revises: e74ff40a1b2a
Create Date: 2023-02-03 15:56:04.620150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c757a5632f69'
down_revision = 'e74ff40a1b2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('from_year', sa.Integer(), nullable=True),
    sa.Column('from_month', sa.Integer(), nullable=True),
    sa.Column('to_year', sa.Integer(), nullable=True),
    sa.Column('to_month', sa.Integer(), nullable=True),
    sa.Column('achievement', sa.String(length=210), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill', sa.String(length=21), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_skills')
    op.drop_table('user_achievements')
    # ### end Alembic commands ###
