"""Add more items to the resume.

Revision ID: d6e5b870dc89
Revises: 08c154310b4a
Create Date: 2023-02-10 14:08:55.189258

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd6e5b870dc89'
down_revision = '08c154310b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_resume_achievements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('achievement', sa.String(length=210), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_resume_education',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('education', sa.String(length=210), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_resume_experience',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('from_year', sa.Integer(), nullable=True),
    sa.Column('from_month', sa.Integer(), nullable=True),
    sa.Column('to_year', sa.Integer(), nullable=True),
    sa.Column('to_month', sa.Integer(), nullable=True),
    sa.Column('job_title', sa.String(length=210), nullable=False),
    sa.Column('organization', sa.String(length=210), nullable=False),
    sa.Column('description', sa.String(length=2100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_resume_portfolio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=210), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_resume_skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill', sa.String(length=21), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_achievements')
    op.drop_table('user_skills')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_job_title', sa.String(length=210), nullable=True))
        batch_op.add_column(sa.Column('resume_bio', sa.String(length=21000), nullable=True))
        batch_op.add_column(sa.Column('resume_desired_salary_usd', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('resume_bitcoiner_question', sa.String(length=2100), nullable=True))
        batch_op.drop_column('desired_salary_usd')
        batch_op.drop_column('bio')
        batch_op.drop_column('bitcoiner_question')
        batch_op.drop_column('job_title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_title', sa.VARCHAR(length=210), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bitcoiner_question', sa.VARCHAR(length=2100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bio', sa.VARCHAR(length=21000), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('desired_salary_usd', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('resume_bitcoiner_question')
        batch_op.drop_column('resume_desired_salary_usd')
        batch_op.drop_column('resume_bio')
        batch_op.drop_column('resume_job_title')

    op.create_table('user_skills',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skill', sa.VARCHAR(length=21), autoincrement=False, nullable=True),
    sa.Column('added_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_skills_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_skills_pkey')
    )
    op.create_table('user_achievements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('from_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('from_month', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('to_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('to_month', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('achievement', sa.VARCHAR(length=210), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_achievements_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_achievements_pkey')
    )
    op.drop_table('user_resume_skills')
    op.drop_table('user_resume_portfolio')
    op.drop_table('user_resume_experience')
    op.drop_table('user_resume_education')
    op.drop_table('user_resume_achievements')
    # ### end Alembic commands ###
