"""Add xpub to campaigns.

Revision ID: d711e375a2ec
Revises: f63c68a9afa1
Create Date: 2022-10-18 09:11:19.552001

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd711e375a2ec'
down_revision = 'f63c68a9afa1'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('xpub', sa.String(length=128), nullable=False))
    op.add_column('campaigns', sa.Column('xpub_index', sa.Integer(), nullable=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'xpub_index')
    op.drop_column('campaigns', 'xpub')
    # ### end Alembic commands ###
