"""Add stall name and description.

Revision ID: d940f3567a1c
Revises: b1b8a655e102
Create Date: 2022-09-27 08:26:46.874789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd940f3567a1c'
down_revision = 'b1b8a655e102'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stall_name', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('stall_description', sa.String(length=21000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stall_description')
    op.drop_column('users', 'stall_name')
    # ### end Alembic commands ###
