"""Add extra shipping per item.

Revision ID: d9a75b8555ed
Revises: 4ba6c5d104b3
Create Date: 2023-08-16 13:32:38.872432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9a75b8555ed'
down_revision = '4ba6c5d104b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_shipping_domestic_usd', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('extra_shipping_worldwide_usd', sa.Float(), nullable=False))
        batch_op.drop_column('shipping_domestic_usd')
        batch_op.drop_column('shipping_worldwide_usd')
        batch_op.drop_column('shipping_from')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_from', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('shipping_worldwide_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('shipping_domestic_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_column('extra_shipping_worldwide_usd')
        batch_op.drop_column('extra_shipping_domestic_usd')

    # ### end Alembic commands ###
