"""Save seller & buyer details.

Revision ID: dc75ae2f8b83
Revises: 2c294f18a1fb
Create Date: 2023-05-17 10:25:48.353947

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dc75ae2f8b83'
down_revision = '2c294f18a1fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('buyer_name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('buyer_address', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('buyer_message', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('buyer_contact', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['seller_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('buyer_contact')
        batch_op.drop_column('buyer_message')
        batch_op.drop_column('buyer_address')
        batch_op.drop_column('buyer_name')
        batch_op.drop_column('seller_id')

    # ### end Alembic commands ###
