"""Alter auction final flow.

Revision ID: e1fdec1dded2
Revises: d940f3567a1c
Create Date: 2022-10-05 14:37:37.642179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1fdec1dded2'
down_revision = 'd940f3567a1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auctions', sa.Column('has_winner', sa.Boolean(), nullable=True))
    op.alter_column('sales', 'contribution_payment_request',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'contribution_payment_request',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.drop_column('auctions', 'has_winner')
    # ### end Alembic commands ###
