"""Store nostr event ID.

Revision ID: e3e271835296
Revises: 85963076ecb7
Create Date: 2023-06-16 11:20:44.087341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3e271835296'
down_revision = '85963076ecb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auctions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nostr_event_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_auctions_nostr_event_id'), ['nostr_event_id'], unique=True)

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nostr_event_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_listings_nostr_event_id'), ['nostr_event_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listings_nostr_event_id'))
        batch_op.drop_column('nostr_event_id')

    with op.batch_alter_table('auctions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auctions_nostr_event_id'))
        batch_op.drop_column('nostr_event_id')

    # ### end Alembic commands ###
