"""add_nostr_columns

Revision ID: e74ff40a1b2a
Revises: 3c9546a68f19
Create Date: 2022-12-19 16:05:00.300138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e74ff40a1b2a'
down_revision = '3c9546a68f19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nostr_private_key', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('nostr_private_key')

    # ### end Alembic commands ###
