"""Campaigns.

Revision ID: f63c68a9afa1
Revises: e1fdec1dded2
Create Date: 2022-10-12 17:01:29.438232

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f63c68a9afa1'
down_revision = 'e1fdec1dded2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auctions', sa.Column('campaign_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_auctions_campaign_id', 'auctions', 'campaigns', ['campaign_id'], ['id'])
    op.add_column('campaigns', sa.Column('name', sa.String(length=210), nullable=False))
    op.drop_column('campaigns', 'title')
    op.drop_column('campaigns', 'start_date')
    op.drop_column('campaigns', 'end_date')
    op.add_column('listings', sa.Column('campaign_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_listings_campaign_id', 'listings', 'campaigns', ['campaign_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_listings_campaign_id', 'listings', type_='foreignkey')
    op.drop_column('listings', 'campaign_id')
    op.add_column('campaigns', sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('title', sa.VARCHAR(length=210), autoincrement=False, nullable=False))
    op.drop_column('campaigns', 'name')
    op.drop_constraint('fk_auctions_campaign_id', 'auctions', type_='foreignkey')
    op.drop_column('auctions', 'campaign_id')
    # ### end Alembic commands ###
