"""Link Lightning account to existing user.

Revision ID: f95a9a40c00d
Revises: a3a6752dda02
Create Date: 2023-04-06 08:09:11.928521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f95a9a40c00d'
down_revision = 'a3a6752dda02'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_lnauth_key', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('new_lnauth_key_k1', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('new_lnauth_key_k1_generated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_new_lnauth_key'), ['new_lnauth_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_new_lnauth_key_k1'), ['new_lnauth_key_k1'], unique=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_new_lnauth_key_k1'))
        batch_op.drop_index(batch_op.f('ix_users_new_lnauth_key'))
        batch_op.drop_column('new_lnauth_key_k1_generated_at')
        batch_op.drop_column('new_lnauth_key_k1')
        batch_op.drop_column('new_lnauth_key')
    # ### end Alembic commands ###
