"""Add shipping estimates.

Revision ID: fc10599148c8
Revises: 51f2466fa172
Create Date: 2022-08-08 08:49:26.127340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc10599148c8'
down_revision = '51f2466fa172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auctions', sa.Column('shipping_estimate_domestic', sa.String(length=64), nullable=True))
    op.add_column('auctions', sa.Column('shipping_estimate_worldwide', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auctions', 'shipping_estimate_worldwide')
    op.drop_column('auctions', 'shipping_estimate_domestic')
    # ### end Alembic commands ###
