"""Store bid event ID.

Revision ID: fcecd5eab28d
Revises: 4a22bfdccc90
Create Date: 2023-06-21 10:13:52.341555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcecd5eab28d'
down_revision = '4a22bfdccc90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nostr_event_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_bids_nostr_event_id'), ['nostr_event_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bids_nostr_event_id'))
        batch_op.drop_column('nostr_event_id')

    # ### end Alembic commands ###
