"""Title, description, duration + Twitter.

Revision ID: 3ab9cd7f2087
Revises: 10f924173b58
Create Date: 2022-04-27 09:48:52.863307

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3ab9cd7f2087'
down_revision = '10f924173b58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('auction_id', sa.Integer(), nullable=False),
    sa.Column('twitter_media_key', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('auctions', sa.Column('title', sa.String(length=32), server_default="", nullable=False))
    op.add_column('auctions', sa.Column('description', sa.String(length=512), server_default="", nullable=False))
    op.add_column('auctions', sa.Column('duration_hours', sa.Integer(), server_default='0', nullable=False))
    op.add_column('auctions', sa.Column('twitter_id', sa.String(length=32), nullable=True))
    op.alter_column('auctions', 'seller_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('auctions', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('auctions', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('bids', 'auction_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bids', 'buyer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('users', 'twitter_username_challenge')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('twitter_username_challenge', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.alter_column('bids', 'buyer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bids', 'auction_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('auctions', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('auctions', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('auctions', 'seller_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('auctions', 'twitter_id')
    op.drop_column('auctions', 'duration_hours')
    op.drop_column('auctions', 'description')
    op.drop_column('auctions', 'title')
    op.drop_table('media')
    # ### end Alembic commands ###
